/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI cards + aging buckets for the dashboard */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payers with payment behavior */
        get: operations["listClients"];
        put?: never;
        /** Add a payer */
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get one payer */
        get: operations["getClient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a payer */
        patch: operations["updateClient"];
        trace?: never;
    };
    "/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices (sorted: overdue first, then by due date) */
        get: operations["listInvoices"];
        put?: never;
        /** Add an invoice; the agent starts planning its chase immediately */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Invoice detail with client summary */
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update invoice fields (incl. status transitions such as pause/resume/write-off) */
        patch: operations["updateInvoice"];
        trace?: never;
    };
    "/invoices/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Agent timeline for one invoice */
        get: operations["listInvoiceActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan cards (what/when/why) and drafts awaiting approval */
        get: operations["getAgentInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/drafts/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve & send a draft (moves to outbox) */
        post: operations["approveDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/drafts/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Skip a draft; the agent replans */
        post: operations["skipDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sent chases, newest first (mock mail client) */
        get: operations["listOutbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paste a payment notification; returns parsed fields + candidate invoice matches */
        post: operations["parsePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a payment and link it to an invoice (settle it) */
        post: operations["reconcilePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace settings incl. demo clock */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update settings */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/simulate/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance the demo clock; the agent acts as of the new time */
        post: operations["simulateAdvance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset demo data to the seeded state */
        post: operations["resetDemo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            message: string;
            fields?: {
                [key: string]: string[];
            };
        };
        /** @enum {string} */
        InvoiceStatus: "draft" | "scheduled" | "chasing" | "paused" | "paid" | "written_off";
        /**
         * @description Escalation ladder (see docs/ux-writing.md)
         * @enum {string}
         */
        ChaseStage: "stage0_reminder" | "stage1_polite" | "stage2_firm" | "stage3_final" | "stage4_escalation";
        /**
         * @description Agent state shown in the invoice table
         * @enum {string}
         */
        AgentState: "idle" | "planning" | "awaiting_approval" | "chasing" | "holding" | "stopped";
        /** @enum {string} */
        Reliability: "pays_on_time" | "usually_late" | "chronically_late";
        PaymentScore: {
            avg_days_late: number;
            reliability: components["schemas"]["Reliability"];
            settled_count: number;
        };
        Client: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: email */
            email: string;
            payment_terms_days: number;
            /** @description e.g. "long-term client, keep warm" — pins the ladder at gentle stages */
            relationship_note?: string;
            payment_score?: components["schemas"]["PaymentScore"];
        };
        ClientInput: {
            name: string;
            /** Format: email */
            email: string;
            /** @default 14 */
            payment_terms_days: number;
            relationship_note?: string;
        };
        ClientUpdate: {
            name?: string;
            /** Format: email */
            email?: string;
            payment_terms_days?: number;
            relationship_note?: string;
        };
        Invoice: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            client_id: number;
            client_name: string;
            number: string;
            amount_cents: number;
            currency: string;
            /** Format: date */
            issued_on: string;
            /** Format: date */
            due_on: string;
            status: components["schemas"]["InvoiceStatus"];
            notes?: string;
            agent_state: components["schemas"]["AgentState"];
            current_stage?: ((string & components["schemas"]["ChaseStage"]) | null) & components["schemas"]["ChaseStage"];
            /** Format: date */
            next_action_on?: string | null;
            /** @description Computed against settings.sim_now (0 when not overdue) */
            days_overdue?: number;
            amount_paid_cents?: number;
            /** Format: date-time */
            created_at: string;
        };
        InvoiceInput: {
            /** Format: int64 */
            client_id: number;
            number: string;
            amount_cents: number;
            currency: string;
            /** Format: date */
            issued_on: string;
            /** Format: date */
            due_on: string;
            notes?: string;
        };
        InvoiceUpdate: {
            number?: string;
            amount_cents?: number;
            /** Format: date */
            due_on?: string;
            notes?: string;
            status?: components["schemas"]["InvoiceStatus"];
        };
        Dashboard: {
            outstanding_cents: number;
            overdue_cents: number;
            /** @description Lifetime sum of payments linked to invoices (the counter) */
            recovered_cents: number;
            /** @description 30-day rolling Days Sales Outstanding */
            dso_days: number;
            counts: {
                overdue: number;
                /** @description Due within 3 days, not yet overdue */
                due_soon: number;
                chasing: number;
                awaiting_approval: number;
            };
            /**
             * Format: date
             * @description The demo clock the numbers are computed against
             */
            sim_now: string;
            /** @description 14-day DSO series for the sparkline */
            dso_trend?: {
                /** Format: date */
                date: string;
                dso_days: number;
            }[];
        };
        Activity: {
            /** Format: int64 */
            id: number;
            invoice_id?: number | null;
            /** @enum {string} */
            type: "invoice_created" | "plan_made" | "draft_ready" | "draft_sent" | "draft_skipped" | "payment_detected" | "invoice_settled" | "chase_paused" | "chase_resumed" | "clock_advanced" | "note";
            message: string;
            /** Format: date-time */
            created_at: string;
        };
        PlanCard: {
            invoice_id: number;
            invoice_number: string;
            client_name: string;
            amount_cents: number;
            stage: components["schemas"]["ChaseStage"];
            /** Format: date */
            planned_on: string;
            /** @description Shown to the user and judges — why this plan */
            reasoning: string;
        };
        Draft: {
            id: number;
            invoice_id: number;
            invoice_number: string;
            client_name: string;
            client_email: string;
            stage: components["schemas"]["ChaseStage"];
            subject: string;
            body: string;
            /** @enum {string} */
            status: "pending" | "approved" | "sent" | "skipped";
            /** Format: date-time */
            created_at: string;
        };
        OutboxEmail: {
            id: number;
            invoice_number: string;
            to_name: string;
            to_email: string;
            subject: string;
            body: string;
            /** Format: date-time */
            sent_at: string;
        };
        AgentInbox: {
            plans: components["schemas"]["PlanCard"][];
            drafts: components["schemas"]["Draft"][];
        };
        PaymentParseResult: {
            parsed: {
                amount_cents: number;
                /** Format: date */
                paid_on?: string | null;
                /** @description Payer name/ID extracted from the text */
                payer_hint?: string | null;
            };
            matches: {
                invoice_id: number;
                invoice_number: string;
                client_name: string;
                amount_cents: number;
                days_overdue?: number;
                /** @enum {string} */
                confidence: "high" | "medium" | "low";
            }[];
        };
        Payment: {
            id: number;
            invoice_id: number;
            amount_cents: number;
            /** Format: date */
            paid_on: string;
            /** @enum {string} */
            source: "paste" | "manual";
            confidence?: string | null;
            raw_text?: string | null;
            invoice_status_after: components["schemas"]["InvoiceStatus"];
        };
        PaymentInput: {
            invoice_id: number;
            amount_cents: number;
            /** Format: date */
            paid_on?: string;
            /**
             * @default manual
             * @enum {string}
             */
            source: "paste" | "manual";
            confidence?: string | null;
            raw_text?: string | null;
        };
        Settings: {
            sender_name: string;
            /** Format: email */
            sender_email: string;
            default_terms_days: number;
            /** @enum {string} */
            global_mode: "approve_each" | "full_auto";
            /** @description True when no LLM provider configured — deterministic templates */
            template_mode: boolean;
            /**
             * Format: date
             * @description Demo clock; null = real today
             */
            sim_now: string | null;
        };
        SettingsUpdate: {
            sender_name?: string;
            /** Format: email */
            sender_email?: string;
            default_terms_days?: number;
            /** @enum {string} */
            global_mode?: "approve_each" | "full_auto";
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflict (duplicate number, wrong state) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                        /** Format: date-time */
                        time: string;
                    };
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    listClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"][];
                };
            };
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                status?: components["schemas"]["InvoiceStatus"];
                client_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"][];
                };
            };
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invoice"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listInvoiceActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAgentInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInbox"];
                };
            };
        };
    };
    approveDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxEmail"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    skipDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
        };
    };
    listOutbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxEmail"][];
                };
            };
        };
    };
    parsePayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentParseResult"];
                };
            };
            /** @description Nothing parseable found */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reconcilePayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentInput"];
            };
        };
        responses: {
            /** @description Settled (or partially applied) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    simulateAdvance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    days?: number;
                    /** Format: date */
                    to_date?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    resetDemo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
}
