// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActivityType.
const (
	ChasePaused     ActivityType = "chase_paused"
	ChaseResumed    ActivityType = "chase_resumed"
	ClockAdvanced   ActivityType = "clock_advanced"
	DraftReady      ActivityType = "draft_ready"
	DraftSent       ActivityType = "draft_sent"
	DraftSkipped    ActivityType = "draft_skipped"
	InvoiceCreated  ActivityType = "invoice_created"
	InvoiceSettled  ActivityType = "invoice_settled"
	Note            ActivityType = "note"
	PaymentDetected ActivityType = "payment_detected"
	PlanMade        ActivityType = "plan_made"
)

// Valid indicates whether the value is a known member of the ActivityType enum.
func (e ActivityType) Valid() bool {
	switch e {
	case ChasePaused:
		return true
	case ChaseResumed:
		return true
	case ClockAdvanced:
		return true
	case DraftReady:
		return true
	case DraftSent:
		return true
	case DraftSkipped:
		return true
	case InvoiceCreated:
		return true
	case InvoiceSettled:
		return true
	case Note:
		return true
	case PaymentDetected:
		return true
	case PlanMade:
		return true
	default:
		return false
	}
}

// Defines values for AgentState.
const (
	AgentStateAwaitingApproval AgentState = "awaiting_approval"
	AgentStateChasing          AgentState = "chasing"
	AgentStateHolding          AgentState = "holding"
	AgentStateIdle             AgentState = "idle"
	AgentStatePlanning         AgentState = "planning"
	AgentStateStopped          AgentState = "stopped"
)

// Valid indicates whether the value is a known member of the AgentState enum.
func (e AgentState) Valid() bool {
	switch e {
	case AgentStateAwaitingApproval:
		return true
	case AgentStateChasing:
		return true
	case AgentStateHolding:
		return true
	case AgentStateIdle:
		return true
	case AgentStatePlanning:
		return true
	case AgentStateStopped:
		return true
	default:
		return false
	}
}

// Defines values for ChaseStage.
const (
	Stage0Reminder   ChaseStage = "stage0_reminder"
	Stage1Polite     ChaseStage = "stage1_polite"
	Stage2Firm       ChaseStage = "stage2_firm"
	Stage3Final      ChaseStage = "stage3_final"
	Stage4Escalation ChaseStage = "stage4_escalation"
)

// Valid indicates whether the value is a known member of the ChaseStage enum.
func (e ChaseStage) Valid() bool {
	switch e {
	case Stage0Reminder:
		return true
	case Stage1Polite:
		return true
	case Stage2Firm:
		return true
	case Stage3Final:
		return true
	case Stage4Escalation:
		return true
	default:
		return false
	}
}

// Defines values for DraftStatus.
const (
	Approved DraftStatus = "approved"
	Pending  DraftStatus = "pending"
	Sent     DraftStatus = "sent"
	Skipped  DraftStatus = "skipped"
)

// Valid indicates whether the value is a known member of the DraftStatus enum.
func (e DraftStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Pending:
		return true
	case Sent:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for InvoiceStatus.
const (
	InvoiceStatusChasing    InvoiceStatus = "chasing"
	InvoiceStatusDraft      InvoiceStatus = "draft"
	InvoiceStatusPaid       InvoiceStatus = "paid"
	InvoiceStatusPaused     InvoiceStatus = "paused"
	InvoiceStatusScheduled  InvoiceStatus = "scheduled"
	InvoiceStatusWrittenOff InvoiceStatus = "written_off"
)

// Valid indicates whether the value is a known member of the InvoiceStatus enum.
func (e InvoiceStatus) Valid() bool {
	switch e {
	case InvoiceStatusChasing:
		return true
	case InvoiceStatusDraft:
		return true
	case InvoiceStatusPaid:
		return true
	case InvoiceStatusPaused:
		return true
	case InvoiceStatusScheduled:
		return true
	case InvoiceStatusWrittenOff:
		return true
	default:
		return false
	}
}

// Defines values for PaymentSource.
const (
	PaymentSourceManual PaymentSource = "manual"
	PaymentSourcePaste  PaymentSource = "paste"
)

// Valid indicates whether the value is a known member of the PaymentSource enum.
func (e PaymentSource) Valid() bool {
	switch e {
	case PaymentSourceManual:
		return true
	case PaymentSourcePaste:
		return true
	default:
		return false
	}
}

// Defines values for PaymentInputSource.
const (
	PaymentInputSourceManual PaymentInputSource = "manual"
	PaymentInputSourcePaste  PaymentInputSource = "paste"
)

// Valid indicates whether the value is a known member of the PaymentInputSource enum.
func (e PaymentInputSource) Valid() bool {
	switch e {
	case PaymentInputSourceManual:
		return true
	case PaymentInputSourcePaste:
		return true
	default:
		return false
	}
}

// Defines values for PaymentParseResultMatchesConfidence.
const (
	High   PaymentParseResultMatchesConfidence = "high"
	Low    PaymentParseResultMatchesConfidence = "low"
	Medium PaymentParseResultMatchesConfidence = "medium"
)

// Valid indicates whether the value is a known member of the PaymentParseResultMatchesConfidence enum.
func (e PaymentParseResultMatchesConfidence) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Medium:
		return true
	default:
		return false
	}
}

// Defines values for Reliability.
const (
	ChronicallyLate Reliability = "chronically_late"
	PaysOnTime      Reliability = "pays_on_time"
	UsuallyLate     Reliability = "usually_late"
)

// Valid indicates whether the value is a known member of the Reliability enum.
func (e Reliability) Valid() bool {
	switch e {
	case ChronicallyLate:
		return true
	case PaysOnTime:
		return true
	case UsuallyLate:
		return true
	default:
		return false
	}
}

// Defines values for SettingsGlobalMode.
const (
	SettingsGlobalModeApproveEach SettingsGlobalMode = "approve_each"
	SettingsGlobalModeFullAuto    SettingsGlobalMode = "full_auto"
)

// Valid indicates whether the value is a known member of the SettingsGlobalMode enum.
func (e SettingsGlobalMode) Valid() bool {
	switch e {
	case SettingsGlobalModeApproveEach:
		return true
	case SettingsGlobalModeFullAuto:
		return true
	default:
		return false
	}
}

// Defines values for SettingsUpdateGlobalMode.
const (
	SettingsUpdateGlobalModeApproveEach SettingsUpdateGlobalMode = "approve_each"
	SettingsUpdateGlobalModeFullAuto    SettingsUpdateGlobalMode = "full_auto"
)

// Valid indicates whether the value is a known member of the SettingsUpdateGlobalMode enum.
func (e SettingsUpdateGlobalMode) Valid() bool {
	switch e {
	case SettingsUpdateGlobalModeApproveEach:
		return true
	case SettingsUpdateGlobalModeFullAuto:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	CreatedAt time.Time    `json:"created_at"`
	Id        int64        `json:"id"`
	InvoiceId *int         `json:"invoice_id,omitempty"`
	Message   string       `json:"message"`
	Type      ActivityType `json:"type"`
}

// ActivityType defines model for Activity.Type.
type ActivityType string

// AgentInbox defines model for AgentInbox.
type AgentInbox struct {
	Drafts []Draft    `json:"drafts"`
	Plans  []PlanCard `json:"plans"`
}

// AgentState Agent state shown in the invoice table
type AgentState string

// ChaseStage Escalation ladder (see docs/ux-writing.md)
type ChaseStage string

// Client defines model for Client.
type Client struct {
	Email            openapi_types.Email `json:"email"`
	Id               int64               `json:"id"`
	Name             string              `json:"name"`
	PaymentScore     *PaymentScore       `json:"payment_score,omitempty"`
	PaymentTermsDays int                 `json:"payment_terms_days"`

	// RelationshipNote e.g. "long-term client, keep warm" — pins the ladder at gentle stages
	RelationshipNote *string `json:"relationship_note,omitempty"`
}

// ClientInput defines model for ClientInput.
type ClientInput struct {
	Email            openapi_types.Email `json:"email"`
	Name             string              `json:"name"`
	PaymentTermsDays *int                `json:"payment_terms_days,omitempty"`
	RelationshipNote *string             `json:"relationship_note,omitempty"`
}

// ClientUpdate defines model for ClientUpdate.
type ClientUpdate struct {
	Email            *openapi_types.Email `json:"email,omitempty"`
	Name             *string              `json:"name,omitempty"`
	PaymentTermsDays *int                 `json:"payment_terms_days,omitempty"`
	RelationshipNote *string              `json:"relationship_note,omitempty"`
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	Counts struct {
		AwaitingApproval int `json:"awaiting_approval"`
		Chasing          int `json:"chasing"`

		// DueSoon Due within 3 days, not yet overdue
		DueSoon int `json:"due_soon"`
		Overdue int `json:"overdue"`
	} `json:"counts"`

	// DsoDays 30-day rolling Days Sales Outstanding
	DsoDays          float32 `json:"dso_days"`
	OutstandingCents int     `json:"outstanding_cents"`
	OverdueCents     int     `json:"overdue_cents"`

	// RecoveredCents Lifetime sum of payments linked to invoices (the counter)
	RecoveredCents int `json:"recovered_cents"`

	// SimNow The demo clock the numbers are computed against
	SimNow openapi_types.Date `json:"sim_now"`
}

// Draft defines model for Draft.
type Draft struct {
	Body          string    `json:"body"`
	ClientEmail   string    `json:"client_email"`
	ClientName    string    `json:"client_name"`
	CreatedAt     time.Time `json:"created_at"`
	Id            int       `json:"id"`
	InvoiceId     int       `json:"invoice_id"`
	InvoiceNumber string    `json:"invoice_number"`

	// Stage Escalation ladder (see docs/ux-writing.md)
	Stage   ChaseStage  `json:"stage"`
	Status  DraftStatus `json:"status"`
	Subject string      `json:"subject"`
}

// DraftStatus defines model for Draft.Status.
type DraftStatus string

// Error defines model for Error.
type Error struct {
	Fields  *map[string][]string `json:"fields,omitempty"`
	Message string               `json:"message"`
}

// Invoice defines model for Invoice.
type Invoice struct {
	// AgentState Agent state shown in the invoice table
	AgentState      AgentState  `json:"agent_state"`
	AmountCents     int         `json:"amount_cents"`
	AmountPaidCents *int        `json:"amount_paid_cents,omitempty"`
	ClientId        int64       `json:"client_id"`
	ClientName      string      `json:"client_name"`
	CreatedAt       time.Time   `json:"created_at"`
	Currency        string      `json:"currency"`
	CurrentStage    *ChaseStage `json:"current_stage,omitempty"`

	// DaysOverdue Computed against settings.sim_now (0 when not overdue)
	DaysOverdue  *int                `json:"days_overdue,omitempty"`
	DueOn        openapi_types.Date  `json:"due_on"`
	Id           int64               `json:"id"`
	IssuedOn     openapi_types.Date  `json:"issued_on"`
	NextActionOn *openapi_types.Date `json:"next_action_on,omitempty"`
	Notes        *string             `json:"notes,omitempty"`
	Number       string              `json:"number"`
	Status       InvoiceStatus       `json:"status"`
}

// InvoiceInput defines model for InvoiceInput.
type InvoiceInput struct {
	AmountCents int                `json:"amount_cents"`
	ClientId    int64              `json:"client_id"`
	Currency    string             `json:"currency"`
	DueOn       openapi_types.Date `json:"due_on"`
	IssuedOn    openapi_types.Date `json:"issued_on"`
	Notes       *string            `json:"notes,omitempty"`
	Number      string             `json:"number"`
}

// InvoiceStatus defines model for InvoiceStatus.
type InvoiceStatus string

// InvoiceUpdate defines model for InvoiceUpdate.
type InvoiceUpdate struct {
	AmountCents *int                `json:"amount_cents,omitempty"`
	DueOn       *openapi_types.Date `json:"due_on,omitempty"`
	Notes       *string             `json:"notes,omitempty"`
	Number      *string             `json:"number,omitempty"`
	Status      *InvoiceStatus      `json:"status,omitempty"`
}

// OutboxEmail defines model for OutboxEmail.
type OutboxEmail struct {
	Body          string    `json:"body"`
	Id            int       `json:"id"`
	InvoiceNumber string    `json:"invoice_number"`
	SentAt        time.Time `json:"sent_at"`
	Subject       string    `json:"subject"`
	ToEmail       string    `json:"to_email"`
	ToName        string    `json:"to_name"`
}

// Payment defines model for Payment.
type Payment struct {
	AmountCents        int                `json:"amount_cents"`
	Confidence         *string            `json:"confidence,omitempty"`
	Id                 int                `json:"id"`
	InvoiceId          int                `json:"invoice_id"`
	InvoiceStatusAfter InvoiceStatus      `json:"invoice_status_after"`
	PaidOn             openapi_types.Date `json:"paid_on"`
	RawText            *string            `json:"raw_text,omitempty"`
	Source             PaymentSource      `json:"source"`
}

// PaymentSource defines model for Payment.Source.
type PaymentSource string

// PaymentInput defines model for PaymentInput.
type PaymentInput struct {
	AmountCents int                 `json:"amount_cents"`
	Confidence  *string             `json:"confidence,omitempty"`
	InvoiceId   int                 `json:"invoice_id"`
	PaidOn      *openapi_types.Date `json:"paid_on,omitempty"`
	RawText     *string             `json:"raw_text,omitempty"`
	Source      *PaymentInputSource `json:"source,omitempty"`
}

// PaymentInputSource defines model for PaymentInput.Source.
type PaymentInputSource string

// PaymentParseResult defines model for PaymentParseResult.
type PaymentParseResult struct {
	Matches []struct {
		AmountCents   int                                 `json:"amount_cents"`
		ClientName    string                              `json:"client_name"`
		Confidence    PaymentParseResultMatchesConfidence `json:"confidence"`
		DaysOverdue   *int                                `json:"days_overdue,omitempty"`
		InvoiceId     int                                 `json:"invoice_id"`
		InvoiceNumber string                              `json:"invoice_number"`
	} `json:"matches"`
	Parsed struct {
		AmountCents int                 `json:"amount_cents"`
		PaidOn      *openapi_types.Date `json:"paid_on,omitempty"`

		// PayerHint Payer name/ID extracted from the text
		PayerHint *string `json:"payer_hint,omitempty"`
	} `json:"parsed"`
}

// PaymentParseResultMatchesConfidence defines model for PaymentParseResult.Matches.Confidence.
type PaymentParseResultMatchesConfidence string

// PaymentScore defines model for PaymentScore.
type PaymentScore struct {
	AvgDaysLate  float32     `json:"avg_days_late"`
	Reliability  Reliability `json:"reliability"`
	SettledCount int         `json:"settled_count"`
}

// PlanCard defines model for PlanCard.
type PlanCard struct {
	AmountCents   int                `json:"amount_cents"`
	ClientName    string             `json:"client_name"`
	InvoiceId     int                `json:"invoice_id"`
	InvoiceNumber string             `json:"invoice_number"`
	PlannedOn     openapi_types.Date `json:"planned_on"`

	// Reasoning Shown to the user and judges — why this plan
	Reasoning string `json:"reasoning"`

	// Stage Escalation ladder (see docs/ux-writing.md)
	Stage ChaseStage `json:"stage"`
}

// Reliability defines model for Reliability.
type Reliability string

// Settings defines model for Settings.
type Settings struct {
	DefaultTermsDays int                 `json:"default_terms_days"`
	GlobalMode       SettingsGlobalMode  `json:"global_mode"`
	SenderEmail      openapi_types.Email `json:"sender_email"`
	SenderName       string              `json:"sender_name"`

	// SimNow Demo clock; null = real today
	SimNow *openapi_types.Date `json:"sim_now"`

	// TemplateMode True when no LLM provider configured — deterministic templates
	TemplateMode bool `json:"template_mode"`
}

// SettingsGlobalMode defines model for Settings.GlobalMode.
type SettingsGlobalMode string

// SettingsUpdate defines model for SettingsUpdate.
type SettingsUpdate struct {
	DefaultTermsDays *int                      `json:"default_terms_days,omitempty"`
	GlobalMode       *SettingsUpdateGlobalMode `json:"global_mode,omitempty"`
	SenderEmail      *openapi_types.Email      `json:"sender_email,omitempty"`
	SenderName       *string                   `json:"sender_name,omitempty"`
}

// SettingsUpdateGlobalMode defines model for SettingsUpdate.GlobalMode.
type SettingsUpdateGlobalMode string

// Id defines model for Id.
type Id = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListInvoicesParams defines parameters for ListInvoices.
type ListInvoicesParams struct {
	Status   *InvoiceStatus `form:"status,omitempty" json:"status,omitempty"`
	ClientId *int64         `form:"client_id,omitempty" json:"client_id,omitempty"`
}

// ParsePaymentJSONBody defines parameters for ParsePayment.
type ParsePaymentJSONBody struct {
	Text string `json:"text"`
}

// SimulateAdvanceJSONBody defines parameters for SimulateAdvance.
type SimulateAdvanceJSONBody struct {
	Days   *int                `json:"days,omitempty"`
	ToDate *openapi_types.Date `json:"to_date,omitempty"`
}

// CreateClientJSONRequestBody defines body for CreateClient for application/json ContentType.
type CreateClientJSONRequestBody = ClientInput

// UpdateClientJSONRequestBody defines body for UpdateClient for application/json ContentType.
type UpdateClientJSONRequestBody = ClientUpdate

// CreateInvoiceJSONRequestBody defines body for CreateInvoice for application/json ContentType.
type CreateInvoiceJSONRequestBody = InvoiceInput

// UpdateInvoiceJSONRequestBody defines body for UpdateInvoice for application/json ContentType.
type UpdateInvoiceJSONRequestBody = InvoiceUpdate

// ReconcilePaymentJSONRequestBody defines body for ReconcilePayment for application/json ContentType.
type ReconcilePaymentJSONRequestBody = PaymentInput

// ParsePaymentJSONRequestBody defines body for ParsePayment for application/json ContentType.
type ParsePaymentJSONRequestBody ParsePaymentJSONBody

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = SettingsUpdate

// SimulateAdvanceJSONRequestBody defines body for SimulateAdvance for application/json ContentType.
type SimulateAdvanceJSONRequestBody SimulateAdvanceJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ApproveDraft Approve & send a draft (moves to outbox)
	// (POST /agent/drafts/{id}/approve)
	ApproveDraft(ctx echo.Context, id Id) error
	// SkipDraft Skip a draft; the agent replans
	// (POST /agent/drafts/{id}/skip)
	SkipDraft(ctx echo.Context, id Id) error
	// GetAgentInbox Plan cards (what/when/why) and drafts awaiting approval
	// (GET /agent/inbox)
	GetAgentInbox(ctx echo.Context) error
	// ListClients List payers with payment behavior
	// (GET /clients)
	ListClients(ctx echo.Context) error
	// CreateClient Add a payer
	// (POST /clients)
	CreateClient(ctx echo.Context) error
	// GetClient Get one payer
	// (GET /clients/{id})
	GetClient(ctx echo.Context, id Id) error
	// UpdateClient Update a payer
	// (PATCH /clients/{id})
	UpdateClient(ctx echo.Context, id Id) error
	// GetDashboard KPI cards + aging buckets for the dashboard
	// (GET /dashboard)
	GetDashboard(ctx echo.Context) error
	// ResetDemo Reset demo data to the seeded state
	// (POST /demo/reset)
	ResetDemo(ctx echo.Context) error
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// ListInvoices List invoices (sorted: overdue first, then by due date)
	// (GET /invoices)
	ListInvoices(ctx echo.Context, params ListInvoicesParams) error
	// CreateInvoice Add an invoice; the agent starts planning its chase immediately
	// (POST /invoices)
	CreateInvoice(ctx echo.Context) error
	// GetInvoice Invoice detail with client summary
	// (GET /invoices/{id})
	GetInvoice(ctx echo.Context, id Id) error
	// UpdateInvoice Update invoice fields (incl. status transitions such as pause/resume/write-off)
	// (PATCH /invoices/{id})
	UpdateInvoice(ctx echo.Context, id Id) error
	// ListInvoiceActivity Agent timeline for one invoice
	// (GET /invoices/{id}/activity)
	ListInvoiceActivity(ctx echo.Context, id Id) error
	// ListOutbox Sent chases, newest first (mock mail client)
	// (GET /outbox)
	ListOutbox(ctx echo.Context) error
	// ReconcilePayment Record a payment and link it to an invoice (settle it)
	// (POST /payments)
	ReconcilePayment(ctx echo.Context) error
	// ParsePayment Paste a payment notification; returns parsed fields + candidate invoice matches
	// (POST /payments/parse)
	ParsePayment(ctx echo.Context) error
	// GetSettings Workspace settings incl. demo clock
	// (GET /settings)
	GetSettings(ctx echo.Context) error
	// UpdateSettings Update settings
	// (PATCH /settings)
	UpdateSettings(ctx echo.Context) error
	// SimulateAdvance Advance the demo clock; the agent acts as of the new time
	// (POST /simulate/advance)
	SimulateAdvance(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ApproveDraft converts echo context to params.
func (w *ServerInterfaceWrapper) ApproveDraft(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ApproveDraft(ctx, id)
	return err
}

// SkipDraft converts echo context to params.
func (w *ServerInterfaceWrapper) SkipDraft(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SkipDraft(ctx, id)
	return err
}

// GetAgentInbox converts echo context to params.
func (w *ServerInterfaceWrapper) GetAgentInbox(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAgentInbox(ctx)
	return err
}

// ListClients converts echo context to params.
func (w *ServerInterfaceWrapper) ListClients(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListClients(ctx)
	return err
}

// CreateClient converts echo context to params.
func (w *ServerInterfaceWrapper) CreateClient(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateClient(ctx)
	return err
}

// GetClient converts echo context to params.
func (w *ServerInterfaceWrapper) GetClient(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetClient(ctx, id)
	return err
}

// UpdateClient converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateClient(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateClient(ctx, id)
	return err
}

// GetDashboard converts echo context to params.
func (w *ServerInterfaceWrapper) GetDashboard(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetDashboard(ctx)
	return err
}

// ResetDemo converts echo context to params.
func (w *ServerInterfaceWrapper) ResetDemo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResetDemo(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// ListInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) ListInvoices(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListInvoicesParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", ctx.QueryParams(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "client_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_id", ctx.QueryParams(), &params.ClientId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter client_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInvoices(ctx, params)
	return err
}

// CreateInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInvoice(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInvoice(ctx)
	return err
}

// GetInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) GetInvoice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInvoice(ctx, id)
	return err
}

// UpdateInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateInvoice(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateInvoice(ctx, id)
	return err
}

// ListInvoiceActivity converts echo context to params.
func (w *ServerInterfaceWrapper) ListInvoiceActivity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInvoiceActivity(ctx, id)
	return err
}

// ListOutbox converts echo context to params.
func (w *ServerInterfaceWrapper) ListOutbox(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListOutbox(ctx)
	return err
}

// ReconcilePayment converts echo context to params.
func (w *ServerInterfaceWrapper) ReconcilePayment(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReconcilePayment(ctx)
	return err
}

// ParsePayment converts echo context to params.
func (w *ServerInterfaceWrapper) ParsePayment(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ParsePayment(ctx)
	return err
}

// GetSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSettings(ctx)
	return err
}

// UpdateSettings converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSettings(ctx)
	return err
}

// SimulateAdvance converts echo context to params.
func (w *ServerInterfaceWrapper) SimulateAdvance(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SimulateAdvance(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)
	router.GET(options.BaseURL+"/dashboard", wrapper.GetDashboard, options.OperationMiddlewares["getDashboard"]...)
	router.GET(options.BaseURL+"/clients", wrapper.ListClients, options.OperationMiddlewares["listClients"]...)
	router.POST(options.BaseURL+"/clients", wrapper.CreateClient, options.OperationMiddlewares["createClient"]...)
	router.GET(options.BaseURL+"/clients/:id", wrapper.GetClient, options.OperationMiddlewares["getClient"]...)
	router.PATCH(options.BaseURL+"/clients/:id", wrapper.UpdateClient, options.OperationMiddlewares["updateClient"]...)
	router.GET(options.BaseURL+"/invoices", wrapper.ListInvoices, options.OperationMiddlewares["listInvoices"]...)
	router.POST(options.BaseURL+"/invoices", wrapper.CreateInvoice, options.OperationMiddlewares["createInvoice"]...)
	router.GET(options.BaseURL+"/invoices/:id", wrapper.GetInvoice, options.OperationMiddlewares["getInvoice"]...)
	router.PATCH(options.BaseURL+"/invoices/:id", wrapper.UpdateInvoice, options.OperationMiddlewares["updateInvoice"]...)
	router.GET(options.BaseURL+"/invoices/:id/activity", wrapper.ListInvoiceActivity, options.OperationMiddlewares["listInvoiceActivity"]...)
	router.GET(options.BaseURL+"/agent/inbox", wrapper.GetAgentInbox, options.OperationMiddlewares["getAgentInbox"]...)
	router.POST(options.BaseURL+"/agent/drafts/:id/approve", wrapper.ApproveDraft, options.OperationMiddlewares["approveDraft"]...)
	router.POST(options.BaseURL+"/agent/drafts/:id/skip", wrapper.SkipDraft, options.OperationMiddlewares["skipDraft"]...)
	router.GET(options.BaseURL+"/outbox", wrapper.ListOutbox, options.OperationMiddlewares["listOutbox"]...)
	router.POST(options.BaseURL+"/payments/parse", wrapper.ParsePayment, options.OperationMiddlewares["parsePayment"]...)
	router.POST(options.BaseURL+"/payments", wrapper.ReconcilePayment, options.OperationMiddlewares["reconcilePayment"]...)
	router.GET(options.BaseURL+"/settings", wrapper.GetSettings, options.OperationMiddlewares["getSettings"]...)
	router.PATCH(options.BaseURL+"/settings", wrapper.UpdateSettings, options.OperationMiddlewares["updateSettings"]...)
	router.POST(options.BaseURL+"/simulate/advance", wrapper.SimulateAdvance, options.OperationMiddlewares["simulateAdvance"]...)
	router.POST(options.BaseURL+"/demo/reset", wrapper.ResetDemo, options.OperationMiddlewares["resetDemo"]...)

}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type NotFoundJSONResponse Error

type ApproveDraftRequestObject struct {
	Id Id `json:"id"`
}

type ApproveDraftResponseObject interface {
	VisitApproveDraftResponse(w http.ResponseWriter) error
}

type ApproveDraft200JSONResponse OutboxEmail

func (response ApproveDraft200JSONResponse) VisitApproveDraftResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ApproveDraft404JSONResponse struct{ NotFoundJSONResponse }

func (response ApproveDraft404JSONResponse) VisitApproveDraftResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ApproveDraft409JSONResponse struct{ ConflictJSONResponse }

func (response ApproveDraft409JSONResponse) VisitApproveDraftResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type SkipDraftRequestObject struct {
	Id Id `json:"id"`
}

type SkipDraftResponseObject interface {
	VisitSkipDraftResponse(w http.ResponseWriter) error
}

type SkipDraft200JSONResponse Draft

func (response SkipDraft200JSONResponse) VisitSkipDraftResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetAgentInboxRequestObject struct {
}

type GetAgentInboxResponseObject interface {
	VisitGetAgentInboxResponse(w http.ResponseWriter) error
}

type GetAgentInbox200JSONResponse AgentInbox

func (response GetAgentInbox200JSONResponse) VisitGetAgentInboxResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListClientsRequestObject struct {
}

type ListClientsResponseObject interface {
	VisitListClientsResponse(w http.ResponseWriter) error
}

type ListClients200JSONResponse []Client

func (response ListClients200JSONResponse) VisitListClientsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateClientRequestObject struct {
	Body *CreateClientJSONRequestBody
}

type CreateClientResponseObject interface {
	VisitCreateClientResponse(w http.ResponseWriter) error
}

type CreateClient201JSONResponse Client

func (response CreateClient201JSONResponse) VisitCreateClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateClient400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateClient400JSONResponse) VisitCreateClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateClient409JSONResponse struct{ ConflictJSONResponse }

func (response CreateClient409JSONResponse) VisitCreateClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetClientRequestObject struct {
	Id Id `json:"id"`
}

type GetClientResponseObject interface {
	VisitGetClientResponse(w http.ResponseWriter) error
}

type GetClient200JSONResponse Client

func (response GetClient200JSONResponse) VisitGetClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetClient404JSONResponse struct{ NotFoundJSONResponse }

func (response GetClient404JSONResponse) VisitGetClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateClientRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateClientJSONRequestBody
}

type UpdateClientResponseObject interface {
	VisitUpdateClientResponse(w http.ResponseWriter) error
}

type UpdateClient200JSONResponse Client

func (response UpdateClient200JSONResponse) VisitUpdateClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateClient400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateClient400JSONResponse) VisitUpdateClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateClient404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateClient404JSONResponse) VisitUpdateClientResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetDashboardRequestObject struct {
}

type GetDashboardResponseObject interface {
	VisitGetDashboardResponse(w http.ResponseWriter) error
}

type GetDashboard200JSONResponse Dashboard

func (response GetDashboard200JSONResponse) VisitGetDashboardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResetDemoRequestObject struct {
}

type ResetDemoResponseObject interface {
	VisitResetDemoResponse(w http.ResponseWriter) error
}

type ResetDemo200JSONResponse struct {
	Ok bool `json:"ok"`
}

func (response ResetDemo200JSONResponse) VisitResetDemoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status string    `json:"status"`
	Time   time.Time `json:"time"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInvoicesRequestObject struct {
	Params ListInvoicesParams
}

type ListInvoicesResponseObject interface {
	VisitListInvoicesResponse(w http.ResponseWriter) error
}

type ListInvoices200JSONResponse []Invoice

func (response ListInvoices200JSONResponse) VisitListInvoicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInvoiceRequestObject struct {
	Body *CreateInvoiceJSONRequestBody
}

type CreateInvoiceResponseObject interface {
	VisitCreateInvoiceResponse(w http.ResponseWriter) error
}

type CreateInvoice201JSONResponse Invoice

func (response CreateInvoice201JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInvoice400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateInvoice400JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInvoice409JSONResponse struct{ ConflictJSONResponse }

func (response CreateInvoice409JSONResponse) VisitCreateInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetInvoiceRequestObject struct {
	Id Id `json:"id"`
}

type GetInvoiceResponseObject interface {
	VisitGetInvoiceResponse(w http.ResponseWriter) error
}

type GetInvoice200JSONResponse Invoice

func (response GetInvoice200JSONResponse) VisitGetInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetInvoice404JSONResponse struct{ NotFoundJSONResponse }

func (response GetInvoice404JSONResponse) VisitGetInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateInvoiceRequestObject struct {
	Id   Id `json:"id"`
	Body *UpdateInvoiceJSONRequestBody
}

type UpdateInvoiceResponseObject interface {
	VisitUpdateInvoiceResponse(w http.ResponseWriter) error
}

type UpdateInvoice200JSONResponse Invoice

func (response UpdateInvoice200JSONResponse) VisitUpdateInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateInvoice400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateInvoice400JSONResponse) VisitUpdateInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateInvoice404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateInvoice404JSONResponse) VisitUpdateInvoiceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListInvoiceActivityRequestObject struct {
	Id Id `json:"id"`
}

type ListInvoiceActivityResponseObject interface {
	VisitListInvoiceActivityResponse(w http.ResponseWriter) error
}

type ListInvoiceActivity200JSONResponse []Activity

func (response ListInvoiceActivity200JSONResponse) VisitListInvoiceActivityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListInvoiceActivity404JSONResponse struct{ NotFoundJSONResponse }

func (response ListInvoiceActivity404JSONResponse) VisitListInvoiceActivityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListOutboxRequestObject struct {
}

type ListOutboxResponseObject interface {
	VisitListOutboxResponse(w http.ResponseWriter) error
}

type ListOutbox200JSONResponse []OutboxEmail

func (response ListOutbox200JSONResponse) VisitListOutboxResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReconcilePaymentRequestObject struct {
	Body *ReconcilePaymentJSONRequestBody
}

type ReconcilePaymentResponseObject interface {
	VisitReconcilePaymentResponse(w http.ResponseWriter) error
}

type ReconcilePayment201JSONResponse Payment

func (response ReconcilePayment201JSONResponse) VisitReconcilePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type ReconcilePayment404JSONResponse struct{ NotFoundJSONResponse }

func (response ReconcilePayment404JSONResponse) VisitReconcilePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ParsePaymentRequestObject struct {
	Body *ParsePaymentJSONRequestBody
}

type ParsePaymentResponseObject interface {
	VisitParsePaymentResponse(w http.ResponseWriter) error
}

type ParsePayment200JSONResponse PaymentParseResult

func (response ParsePayment200JSONResponse) VisitParsePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ParsePayment422JSONResponse Error

func (response ParsePayment422JSONResponse) VisitParsePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetSettingsRequestObject struct {
}

type GetSettingsResponseObject interface {
	VisitGetSettingsResponse(w http.ResponseWriter) error
}

type GetSettings200JSONResponse Settings

func (response GetSettings200JSONResponse) VisitGetSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettingsRequestObject struct {
	Body *UpdateSettingsJSONRequestBody
}

type UpdateSettingsResponseObject interface {
	VisitUpdateSettingsResponse(w http.ResponseWriter) error
}

type UpdateSettings200JSONResponse Settings

func (response UpdateSettings200JSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSettings400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSettings400JSONResponse) VisitUpdateSettingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SimulateAdvanceRequestObject struct {
	Body *SimulateAdvanceJSONRequestBody
}

type SimulateAdvanceResponseObject interface {
	VisitSimulateAdvanceResponse(w http.ResponseWriter) error
}

type SimulateAdvance200JSONResponse Settings

func (response SimulateAdvance200JSONResponse) VisitSimulateAdvanceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ApproveDraft Approve & send a draft (moves to outbox)
	// (POST /agent/drafts/{id}/approve)
	ApproveDraft(ctx context.Context, request ApproveDraftRequestObject) (ApproveDraftResponseObject, error)
	// SkipDraft Skip a draft; the agent replans
	// (POST /agent/drafts/{id}/skip)
	SkipDraft(ctx context.Context, request SkipDraftRequestObject) (SkipDraftResponseObject, error)
	// GetAgentInbox Plan cards (what/when/why) and drafts awaiting approval
	// (GET /agent/inbox)
	GetAgentInbox(ctx context.Context, request GetAgentInboxRequestObject) (GetAgentInboxResponseObject, error)
	// ListClients List payers with payment behavior
	// (GET /clients)
	ListClients(ctx context.Context, request ListClientsRequestObject) (ListClientsResponseObject, error)
	// CreateClient Add a payer
	// (POST /clients)
	CreateClient(ctx context.Context, request CreateClientRequestObject) (CreateClientResponseObject, error)
	// GetClient Get one payer
	// (GET /clients/{id})
	GetClient(ctx context.Context, request GetClientRequestObject) (GetClientResponseObject, error)
	// UpdateClient Update a payer
	// (PATCH /clients/{id})
	UpdateClient(ctx context.Context, request UpdateClientRequestObject) (UpdateClientResponseObject, error)
	// GetDashboard KPI cards + aging buckets for the dashboard
	// (GET /dashboard)
	GetDashboard(ctx context.Context, request GetDashboardRequestObject) (GetDashboardResponseObject, error)
	// ResetDemo Reset demo data to the seeded state
	// (POST /demo/reset)
	ResetDemo(ctx context.Context, request ResetDemoRequestObject) (ResetDemoResponseObject, error)
	// GetHealth Liveness probe
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// ListInvoices List invoices (sorted: overdue first, then by due date)
	// (GET /invoices)
	ListInvoices(ctx context.Context, request ListInvoicesRequestObject) (ListInvoicesResponseObject, error)
	// CreateInvoice Add an invoice; the agent starts planning its chase immediately
	// (POST /invoices)
	CreateInvoice(ctx context.Context, request CreateInvoiceRequestObject) (CreateInvoiceResponseObject, error)
	// GetInvoice Invoice detail with client summary
	// (GET /invoices/{id})
	GetInvoice(ctx context.Context, request GetInvoiceRequestObject) (GetInvoiceResponseObject, error)
	// UpdateInvoice Update invoice fields (incl. status transitions such as pause/resume/write-off)
	// (PATCH /invoices/{id})
	UpdateInvoice(ctx context.Context, request UpdateInvoiceRequestObject) (UpdateInvoiceResponseObject, error)
	// ListInvoiceActivity Agent timeline for one invoice
	// (GET /invoices/{id}/activity)
	ListInvoiceActivity(ctx context.Context, request ListInvoiceActivityRequestObject) (ListInvoiceActivityResponseObject, error)
	// ListOutbox Sent chases, newest first (mock mail client)
	// (GET /outbox)
	ListOutbox(ctx context.Context, request ListOutboxRequestObject) (ListOutboxResponseObject, error)
	// ReconcilePayment Record a payment and link it to an invoice (settle it)
	// (POST /payments)
	ReconcilePayment(ctx context.Context, request ReconcilePaymentRequestObject) (ReconcilePaymentResponseObject, error)
	// ParsePayment Paste a payment notification; returns parsed fields + candidate invoice matches
	// (POST /payments/parse)
	ParsePayment(ctx context.Context, request ParsePaymentRequestObject) (ParsePaymentResponseObject, error)
	// GetSettings Workspace settings incl. demo clock
	// (GET /settings)
	GetSettings(ctx context.Context, request GetSettingsRequestObject) (GetSettingsResponseObject, error)
	// UpdateSettings Update settings
	// (PATCH /settings)
	UpdateSettings(ctx context.Context, request UpdateSettingsRequestObject) (UpdateSettingsResponseObject, error)
	// SimulateAdvance Advance the demo clock; the agent acts as of the new time
	// (POST /simulate/advance)
	SimulateAdvance(ctx context.Context, request SimulateAdvanceRequestObject) (SimulateAdvanceResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ApproveDraft operation middleware
func (sh *strictHandler) ApproveDraft(ctx echo.Context, id Id) error {
	var request ApproveDraftRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApproveDraft(ctx.Request().Context(), request.(ApproveDraftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApproveDraft")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ApproveDraftResponseObject); ok {
		return validResponse.VisitApproveDraftResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SkipDraft operation middleware
func (sh *strictHandler) SkipDraft(ctx echo.Context, id Id) error {
	var request SkipDraftRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SkipDraft(ctx.Request().Context(), request.(SkipDraftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SkipDraft")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SkipDraftResponseObject); ok {
		return validResponse.VisitSkipDraftResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetAgentInbox operation middleware
func (sh *strictHandler) GetAgentInbox(ctx echo.Context) error {
	var request GetAgentInboxRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentInbox(ctx.Request().Context(), request.(GetAgentInboxRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentInbox")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAgentInboxResponseObject); ok {
		return validResponse.VisitGetAgentInboxResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListClients operation middleware
func (sh *strictHandler) ListClients(ctx echo.Context) error {
	var request ListClientsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListClients(ctx.Request().Context(), request.(ListClientsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListClients")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListClientsResponseObject); ok {
		return validResponse.VisitListClientsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateClient operation middleware
func (sh *strictHandler) CreateClient(ctx echo.Context) error {
	var request CreateClientRequestObject

	var body CreateClientJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateClient(ctx.Request().Context(), request.(CreateClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateClientResponseObject); ok {
		return validResponse.VisitCreateClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetClient operation middleware
func (sh *strictHandler) GetClient(ctx echo.Context, id Id) error {
	var request GetClientRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetClient(ctx.Request().Context(), request.(GetClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetClientResponseObject); ok {
		return validResponse.VisitGetClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateClient operation middleware
func (sh *strictHandler) UpdateClient(ctx echo.Context, id Id) error {
	var request UpdateClientRequestObject

	request.Id = id

	var body UpdateClientJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateClient(ctx.Request().Context(), request.(UpdateClientRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateClient")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateClientResponseObject); ok {
		return validResponse.VisitUpdateClientResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetDashboard operation middleware
func (sh *strictHandler) GetDashboard(ctx echo.Context) error {
	var request GetDashboardRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetDashboard(ctx.Request().Context(), request.(GetDashboardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDashboard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDashboardResponseObject); ok {
		return validResponse.VisitGetDashboardResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ResetDemo operation middleware
func (sh *strictHandler) ResetDemo(ctx echo.Context) error {
	var request ResetDemoRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ResetDemo(ctx.Request().Context(), request.(ResetDemoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResetDemo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ResetDemoResponseObject); ok {
		return validResponse.VisitResetDemoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListInvoices operation middleware
func (sh *strictHandler) ListInvoices(ctx echo.Context, params ListInvoicesParams) error {
	var request ListInvoicesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvoices(ctx.Request().Context(), request.(ListInvoicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvoices")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListInvoicesResponseObject); ok {
		return validResponse.VisitListInvoicesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateInvoice operation middleware
func (sh *strictHandler) CreateInvoice(ctx echo.Context) error {
	var request CreateInvoiceRequestObject

	var body CreateInvoiceJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInvoice(ctx.Request().Context(), request.(CreateInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateInvoiceResponseObject); ok {
		return validResponse.VisitCreateInvoiceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetInvoice operation middleware
func (sh *strictHandler) GetInvoice(ctx echo.Context, id Id) error {
	var request GetInvoiceRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetInvoice(ctx.Request().Context(), request.(GetInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetInvoiceResponseObject); ok {
		return validResponse.VisitGetInvoiceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateInvoice operation middleware
func (sh *strictHandler) UpdateInvoice(ctx echo.Context, id Id) error {
	var request UpdateInvoiceRequestObject

	request.Id = id

	var body UpdateInvoiceJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateInvoice(ctx.Request().Context(), request.(UpdateInvoiceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateInvoice")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateInvoiceResponseObject); ok {
		return validResponse.VisitUpdateInvoiceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListInvoiceActivity operation middleware
func (sh *strictHandler) ListInvoiceActivity(ctx echo.Context, id Id) error {
	var request ListInvoiceActivityRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvoiceActivity(ctx.Request().Context(), request.(ListInvoiceActivityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvoiceActivity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListInvoiceActivityResponseObject); ok {
		return validResponse.VisitListInvoiceActivityResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListOutbox operation middleware
func (sh *strictHandler) ListOutbox(ctx echo.Context) error {
	var request ListOutboxRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListOutbox(ctx.Request().Context(), request.(ListOutboxRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListOutbox")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListOutboxResponseObject); ok {
		return validResponse.VisitListOutboxResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ReconcilePayment operation middleware
func (sh *strictHandler) ReconcilePayment(ctx echo.Context) error {
	var request ReconcilePaymentRequestObject

	var body ReconcilePaymentJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReconcilePayment(ctx.Request().Context(), request.(ReconcilePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReconcilePayment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ReconcilePaymentResponseObject); ok {
		return validResponse.VisitReconcilePaymentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ParsePayment operation middleware
func (sh *strictHandler) ParsePayment(ctx echo.Context) error {
	var request ParsePaymentRequestObject

	var body ParsePaymentJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ParsePayment(ctx.Request().Context(), request.(ParsePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ParsePayment")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ParsePaymentResponseObject); ok {
		return validResponse.VisitParsePaymentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSettings operation middleware
func (sh *strictHandler) GetSettings(ctx echo.Context) error {
	var request GetSettingsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSettings(ctx.Request().Context(), request.(GetSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSettings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSettingsResponseObject); ok {
		return validResponse.VisitGetSettingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateSettings operation middleware
func (sh *strictHandler) UpdateSettings(ctx echo.Context) error {
	var request UpdateSettingsRequestObject

	var body UpdateSettingsJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSettings(ctx.Request().Context(), request.(UpdateSettingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSettings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateSettingsResponseObject); ok {
		return validResponse.VisitUpdateSettingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SimulateAdvance operation middleware
func (sh *strictHandler) SimulateAdvance(ctx echo.Context) error {
	var request SimulateAdvanceRequestObject

	var body SimulateAdvanceJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SimulateAdvance(ctx.Request().Context(), request.(SimulateAdvanceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SimulateAdvance")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SimulateAdvanceResponseObject); ok {
		return validResponse.VisitSimulateAdvanceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
