// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package db

import (
	"context"
	"database/sql"
)

const countSentChases = `-- name: CountSentChases :one
SELECT COUNT(*) FROM outbox_emails WHERE invoice_id = ?
`

func (q *Queries) CountSentChases(ctx context.Context, invoiceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSentChases, invoiceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDraftWithInvoice = `-- name: GetDraftWithInvoice :one
SELECT d.id, d.invoice_id, d.stage, d.subject, d.body, d.status, d.created_at, d.sent_at, i.number AS invoice_number, i.amount_cents, i.currency, i.due_on,
       c.name AS client_name, c.email AS client_email
  FROM email_drafts d
  JOIN invoices i ON i.id = d.invoice_id
  JOIN clients c ON c.id = i.client_id
 WHERE d.id = ?
`

type GetDraftWithInvoiceRow struct {
	ID            int64
	InvoiceID     int64
	Stage         string
	Subject       string
	Body          string
	Status        string
	CreatedAt     string
	SentAt        sql.NullString
	InvoiceNumber string
	AmountCents   int64
	Currency      string
	DueOn         string
	ClientName    string
	ClientEmail   string
}

func (q *Queries) GetDraftWithInvoice(ctx context.Context, id int64) (GetDraftWithInvoiceRow, error) {
	row := q.db.QueryRowContext(ctx, getDraftWithInvoice, id)
	var i GetDraftWithInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Stage,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.SentAt,
		&i.InvoiceNumber,
		&i.AmountCents,
		&i.Currency,
		&i.DueOn,
		&i.ClientName,
		&i.ClientEmail,
	)
	return i, err
}

const hasPendingDraftForStage = `-- name: HasPendingDraftForStage :one
SELECT COUNT(*) FROM email_drafts WHERE invoice_id = ? AND stage = ? AND status = 'pending'
`

type HasPendingDraftForStageParams struct {
	InvoiceID int64
	Stage     string
}

func (q *Queries) HasPendingDraftForStage(ctx context.Context, arg HasPendingDraftForStageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasPendingDraftForStage, arg.InvoiceID, arg.Stage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOpenInvoicesWithPayer = `-- name: ListOpenInvoicesWithPayer :many
SELECT i.id, i.client_id, i.number, i.amount_cents, i.amount_paid_cents, i.currency, i.issued_on, i.due_on, i.status, i.notes, i.agent_state, i.current_stage, i.next_action_on, i.created_at, c.name AS client_name, c.email AS client_email, c.relationship_note
  FROM invoices i
  JOIN clients c ON c.id = i.client_id
 WHERE i.status IN ('scheduled', 'chasing')
 ORDER BY i.due_on ASC
`

type ListOpenInvoicesWithPayerRow struct {
	ID               int64
	ClientID         int64
	Number           string
	AmountCents      int64
	AmountPaidCents  int64
	Currency         string
	IssuedOn         string
	DueOn            string
	Status           string
	Notes            string
	AgentState       string
	CurrentStage     sql.NullString
	NextActionOn     sql.NullString
	CreatedAt        string
	ClientName       string
	ClientEmail      string
	RelationshipNote string
}

func (q *Queries) ListOpenInvoicesWithPayer(ctx context.Context) ([]ListOpenInvoicesWithPayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenInvoicesWithPayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenInvoicesWithPayerRow
	for rows.Next() {
		var i ListOpenInvoicesWithPayerRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Number,
			&i.AmountCents,
			&i.AmountPaidCents,
			&i.Currency,
			&i.IssuedOn,
			&i.DueOn,
			&i.Status,
			&i.Notes,
			&i.AgentState,
			&i.CurrentStage,
			&i.NextActionOn,
			&i.CreatedAt,
			&i.ClientName,
			&i.ClientEmail,
			&i.RelationshipNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutbox = `-- name: ListOutbox :many
SELECT id, invoice_id, draft_id, invoice_number, to_name, to_email, subject, body, sent_at FROM outbox_emails ORDER BY sent_at DESC, id DESC
`

func (q *Queries) ListOutbox(ctx context.Context) ([]OutboxEmail, error) {
	rows, err := q.db.QueryContext(ctx, listOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEmail
	for rows.Next() {
		var i OutboxEmail
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.DraftID,
			&i.InvoiceNumber,
			&i.ToName,
			&i.ToEmail,
			&i.Subject,
			&i.Body,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDraftsWithInvoice = `-- name: ListPendingDraftsWithInvoice :many
SELECT d.id, d.invoice_id, d.stage, d.subject, d.body, d.status, d.created_at, d.sent_at, i.number AS invoice_number, i.amount_cents, i.currency, i.due_on,
       c.name AS client_name, c.email AS client_email
  FROM email_drafts d
  JOIN invoices i ON i.id = d.invoice_id
  JOIN clients c ON c.id = i.client_id
 WHERE d.status = 'pending'
 ORDER BY d.created_at DESC, d.id DESC
`

type ListPendingDraftsWithInvoiceRow struct {
	ID            int64
	InvoiceID     int64
	Stage         string
	Subject       string
	Body          string
	Status        string
	CreatedAt     string
	SentAt        sql.NullString
	InvoiceNumber string
	AmountCents   int64
	Currency      string
	DueOn         string
	ClientName    string
	ClientEmail   string
}

func (q *Queries) ListPendingDraftsWithInvoice(ctx context.Context) ([]ListPendingDraftsWithInvoiceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDraftsWithInvoice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingDraftsWithInvoiceRow
	for rows.Next() {
		var i ListPendingDraftsWithInvoiceRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Stage,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.SentAt,
			&i.InvoiceNumber,
			&i.AmountCents,
			&i.Currency,
			&i.DueOn,
			&i.ClientName,
			&i.ClientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDraftSent = `-- name: MarkDraftSent :exec
UPDATE email_drafts SET status = 'sent', sent_at = ? WHERE id = ?
`

type MarkDraftSentParams struct {
	SentAt sql.NullString
	ID     int64
}

func (q *Queries) MarkDraftSent(ctx context.Context, arg MarkDraftSentParams) error {
	_, err := q.db.ExecContext(ctx, markDraftSent, arg.SentAt, arg.ID)
	return err
}

const markDraftStatus = `-- name: MarkDraftStatus :exec
UPDATE email_drafts SET status = ? WHERE id = ?
`

type MarkDraftStatusParams struct {
	Status string
	ID     int64
}

func (q *Queries) MarkDraftStatus(ctx context.Context, arg MarkDraftStatusParams) error {
	_, err := q.db.ExecContext(ctx, markDraftStatus, arg.Status, arg.ID)
	return err
}

const paymentStats = `-- name: PaymentStats :many
SELECT p.invoice_id, p.amount_cents, p.paid_on, i.client_id, i.issued_on, i.due_on
  FROM payments p JOIN invoices i ON i.id = p.invoice_id
 WHERE i.status = 'paid'
`

type PaymentStatsRow struct {
	InvoiceID   sql.NullInt64
	AmountCents int64
	PaidOn      string
	ClientID    int64
	IssuedOn    string
	DueOn       string
}

func (q *Queries) PaymentStats(ctx context.Context) ([]PaymentStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, paymentStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentStatsRow
	for rows.Next() {
		var i PaymentStatsRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AmountCents,
			&i.PaidOn,
			&i.ClientID,
			&i.IssuedOn,
			&i.DueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInvoiceAgentState = `-- name: SetInvoiceAgentState :exec
UPDATE invoices SET agent_state = ? WHERE id = ?
`

type SetInvoiceAgentStateParams struct {
	AgentState string
	ID         int64
}

func (q *Queries) SetInvoiceAgentState(ctx context.Context, arg SetInvoiceAgentStateParams) error {
	_, err := q.db.ExecContext(ctx, setInvoiceAgentState, arg.AgentState, arg.ID)
	return err
}

const setInvoiceChase = `-- name: SetInvoiceChase :exec
UPDATE invoices
   SET current_stage = ?, next_action_on = ?, agent_state = ?
 WHERE id = ?
`

type SetInvoiceChaseParams struct {
	CurrentStage sql.NullString
	NextActionOn sql.NullString
	AgentState   string
	ID           int64
}

func (q *Queries) SetInvoiceChase(ctx context.Context, arg SetInvoiceChaseParams) error {
	_, err := q.db.ExecContext(ctx, setInvoiceChase,
		arg.CurrentStage,
		arg.NextActionOn,
		arg.AgentState,
		arg.ID,
	)
	return err
}
