// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (name, email, payment_terms_days, relationship_note)
VALUES (?, ?, ?, ?)
RETURNING id, name, email, payment_terms_days, relationship_note, created_at
`

type CreateClientParams struct {
	Name             string
	Email            string
	PaymentTermsDays int64
	RelationshipNote string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, createClient,
		arg.Name,
		arg.Email,
		arg.PaymentTermsDays,
		arg.RelationshipNote,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PaymentTermsDays,
		&i.RelationshipNote,
		&i.CreatedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, name, email, payment_terms_days, relationship_note, created_at FROM clients WHERE id = ?
`

func (q *Queries) GetClient(ctx context.Context, id int64) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PaymentTermsDays,
		&i.RelationshipNote,
		&i.CreatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, email, payment_terms_days, relationship_note, created_at FROM clients ORDER BY name
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PaymentTermsDays,
			&i.RelationshipNote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
   SET name = COALESCE(?1, name),
       email = COALESCE(?2, email),
       payment_terms_days = COALESCE(?3, payment_terms_days),
       relationship_note = COALESCE(?4, relationship_note)
 WHERE id = ?5
RETURNING id, name, email, payment_terms_days, relationship_note, created_at
`

type UpdateClientParams struct {
	Name             sql.NullString
	Email            sql.NullString
	PaymentTermsDays sql.NullInt64
	RelationshipNote sql.NullString
	ID               int64
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, updateClient,
		arg.Name,
		arg.Email,
		arg.PaymentTermsDays,
		arg.RelationshipNote,
		arg.ID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PaymentTermsDays,
		&i.RelationshipNote,
		&i.CreatedAt,
	)
	return i, err
}
