// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package db

import (
	"context"
	"database/sql"
)

const countInvoiceNumberForClient = `-- name: CountInvoiceNumberForClient :one
SELECT COUNT(*) FROM invoices WHERE client_id = ? AND number = ? AND id != ?3
`

type CountInvoiceNumberForClientParams struct {
	ClientID  int64
	Number    string
	ExcludeID sql.NullInt64
}

func (q *Queries) CountInvoiceNumberForClient(ctx context.Context, arg CountInvoiceNumberForClientParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInvoiceNumberForClient, arg.ClientID, arg.Number, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (client_id, number, amount_cents, currency, issued_on, due_on, notes, status, agent_state)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, client_id, number, amount_cents, amount_paid_cents, currency, issued_on, due_on, status, notes, agent_state, current_stage, next_action_on, created_at
`

type CreateInvoiceParams struct {
	ClientID    int64
	Number      string
	AmountCents int64
	Currency    string
	IssuedOn    string
	DueOn       string
	Notes       string
	Status      string
	AgentState  string
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.ClientID,
		arg.Number,
		arg.AmountCents,
		arg.Currency,
		arg.IssuedOn,
		arg.DueOn,
		arg.Notes,
		arg.Status,
		arg.AgentState,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Number,
		&i.AmountCents,
		&i.AmountPaidCents,
		&i.Currency,
		&i.IssuedOn,
		&i.DueOn,
		&i.Status,
		&i.Notes,
		&i.AgentState,
		&i.CurrentStage,
		&i.NextActionOn,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT i.id, i.client_id, i.number, i.amount_cents, i.amount_paid_cents, i.currency, i.issued_on, i.due_on, i.status, i.notes, i.agent_state, i.current_stage, i.next_action_on, i.created_at, c.name AS client_name
  FROM invoices i
  JOIN clients c ON c.id = i.client_id
 WHERE i.id = ?
`

type GetInvoiceRow struct {
	ID              int64
	ClientID        int64
	Number          string
	AmountCents     int64
	AmountPaidCents int64
	Currency        string
	IssuedOn        string
	DueOn           string
	Status          string
	Notes           string
	AgentState      string
	CurrentStage    sql.NullString
	NextActionOn    sql.NullString
	CreatedAt       string
	ClientName      string
}

func (q *Queries) GetInvoice(ctx context.Context, id int64) (GetInvoiceRow, error) {
	row := q.db.QueryRowContext(ctx, getInvoice, id)
	var i GetInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Number,
		&i.AmountCents,
		&i.AmountPaidCents,
		&i.Currency,
		&i.IssuedOn,
		&i.DueOn,
		&i.Status,
		&i.Notes,
		&i.AgentState,
		&i.CurrentStage,
		&i.NextActionOn,
		&i.CreatedAt,
		&i.ClientName,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.client_id, i.number, i.amount_cents, i.amount_paid_cents, i.currency, i.issued_on, i.due_on, i.status, i.notes, i.agent_state, i.current_stage, i.next_action_on, i.created_at, c.name AS client_name
  FROM invoices i
  JOIN clients c ON c.id = i.client_id
 ORDER BY i.due_on ASC
`

type ListInvoicesRow struct {
	ID              int64
	ClientID        int64
	Number          string
	AmountCents     int64
	AmountPaidCents int64
	Currency        string
	IssuedOn        string
	DueOn           string
	Status          string
	Notes           string
	AgentState      string
	CurrentStage    sql.NullString
	NextActionOn    sql.NullString
	CreatedAt       string
	ClientName      string
}

func (q *Queries) ListInvoices(ctx context.Context) ([]ListInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesRow
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Number,
			&i.AmountCents,
			&i.AmountPaidCents,
			&i.Currency,
			&i.IssuedOn,
			&i.DueOn,
			&i.Status,
			&i.Notes,
			&i.AgentState,
			&i.CurrentStage,
			&i.NextActionOn,
			&i.CreatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByClient = `-- name: ListInvoicesByClient :many
SELECT i.id, i.client_id, i.number, i.amount_cents, i.amount_paid_cents, i.currency, i.issued_on, i.due_on, i.status, i.notes, i.agent_state, i.current_stage, i.next_action_on, i.created_at, c.name AS client_name
  FROM invoices i
  JOIN clients c ON c.id = i.client_id
 WHERE i.client_id = ?
 ORDER BY i.due_on ASC
`

type ListInvoicesByClientRow struct {
	ID              int64
	ClientID        int64
	Number          string
	AmountCents     int64
	AmountPaidCents int64
	Currency        string
	IssuedOn        string
	DueOn           string
	Status          string
	Notes           string
	AgentState      string
	CurrentStage    sql.NullString
	NextActionOn    sql.NullString
	CreatedAt       string
	ClientName      string
}

func (q *Queries) ListInvoicesByClient(ctx context.Context, clientID int64) ([]ListInvoicesByClientRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesByClientRow
	for rows.Next() {
		var i ListInvoicesByClientRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Number,
			&i.AmountCents,
			&i.AmountPaidCents,
			&i.Currency,
			&i.IssuedOn,
			&i.DueOn,
			&i.Status,
			&i.Notes,
			&i.AgentState,
			&i.CurrentStage,
			&i.NextActionOn,
			&i.CreatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByStatus = `-- name: ListInvoicesByStatus :many
SELECT i.id, i.client_id, i.number, i.amount_cents, i.amount_paid_cents, i.currency, i.issued_on, i.due_on, i.status, i.notes, i.agent_state, i.current_stage, i.next_action_on, i.created_at, c.name AS client_name
  FROM invoices i
  JOIN clients c ON c.id = i.client_id
 WHERE i.status = ?
 ORDER BY i.due_on ASC
`

type ListInvoicesByStatusRow struct {
	ID              int64
	ClientID        int64
	Number          string
	AmountCents     int64
	AmountPaidCents int64
	Currency        string
	IssuedOn        string
	DueOn           string
	Status          string
	Notes           string
	AgentState      string
	CurrentStage    sql.NullString
	NextActionOn    sql.NullString
	CreatedAt       string
	ClientName      string
}

func (q *Queries) ListInvoicesByStatus(ctx context.Context, status string) ([]ListInvoicesByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesByStatusRow
	for rows.Next() {
		var i ListInvoicesByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Number,
			&i.AmountCents,
			&i.AmountPaidCents,
			&i.Currency,
			&i.IssuedOn,
			&i.DueOn,
			&i.Status,
			&i.Notes,
			&i.AgentState,
			&i.CurrentStage,
			&i.NextActionOn,
			&i.CreatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceFields = `-- name: UpdateInvoiceFields :one
UPDATE invoices
   SET number        = COALESCE(?1, number),
       amount_cents  = COALESCE(?2, amount_cents),
       due_on        = COALESCE(?3, due_on),
       notes         = COALESCE(?4, notes),
       status        = COALESCE(?5, status),
       agent_state   = COALESCE(?6, agent_state),
       current_stage = COALESCE(?7, current_stage),
       next_action_on = ?8,
       amount_paid_cents = COALESCE(?9, amount_paid_cents)
 WHERE id = ?10
RETURNING id, client_id, number, amount_cents, amount_paid_cents, currency, issued_on, due_on, status, notes, agent_state, current_stage, next_action_on, created_at
`

type UpdateInvoiceFieldsParams struct {
	Number          sql.NullString
	AmountCents     sql.NullInt64
	DueOn           sql.NullString
	Notes           sql.NullString
	Status          sql.NullString
	AgentState      sql.NullString
	CurrentStage    sql.NullString
	NextActionOn    sql.NullString
	AmountPaidCents sql.NullInt64
	ID              int64
}

func (q *Queries) UpdateInvoiceFields(ctx context.Context, arg UpdateInvoiceFieldsParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceFields,
		arg.Number,
		arg.AmountCents,
		arg.DueOn,
		arg.Notes,
		arg.Status,
		arg.AgentState,
		arg.CurrentStage,
		arg.NextActionOn,
		arg.AmountPaidCents,
		arg.ID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Number,
		&i.AmountCents,
		&i.AmountPaidCents,
		&i.Currency,
		&i.IssuedOn,
		&i.DueOn,
		&i.Status,
		&i.Notes,
		&i.AgentState,
		&i.CurrentStage,
		&i.NextActionOn,
		&i.CreatedAt,
	)
	return i, err
}
