// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: misc.sql

package db

import (
	"context"
	"database/sql"
)

const applyPayment = `-- name: ApplyPayment :exec
UPDATE invoices
   SET amount_paid_cents = amount_paid_cents + ?,
       status = ?,
       agent_state = 'stopped',
       current_stage = NULL,
       next_action_on = NULL
 WHERE id = ?
`

type ApplyPaymentParams struct {
	AmountPaidCents int64
	Status          string
	ID              int64
}

func (q *Queries) ApplyPayment(ctx context.Context, arg ApplyPaymentParams) error {
	_, err := q.db.ExecContext(ctx, applyPayment, arg.AmountPaidCents, arg.Status, arg.ID)
	return err
}

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingDrafts = `-- name: CountPendingDrafts :one
SELECT COUNT(*) FROM email_drafts WHERE status = 'pending'
`

func (q *Queries) CountPendingDrafts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingDrafts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (invoice_id, amount_cents, paid_on, source, confidence, raw_text)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, invoice_id, amount_cents, paid_on, source, confidence, raw_text, created_at
`

type CreatePaymentParams struct {
	InvoiceID   sql.NullInt64
	AmountCents int64
	PaidOn      string
	Source      string
	Confidence  sql.NullString
	RawText     sql.NullString
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.InvoiceID,
		arg.AmountCents,
		arg.PaidOn,
		arg.Source,
		arg.Confidence,
		arg.RawText,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AmountCents,
		&i.PaidOn,
		&i.Source,
		&i.Confidence,
		&i.RawText,
		&i.CreatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, sender_name, sender_email, default_terms_days, global_mode, sim_now FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SenderName,
		&i.SenderEmail,
		&i.DefaultTermsDays,
		&i.GlobalMode,
		&i.SimNow,
	)
	return i, err
}

const initSettings = `-- name: InitSettings :exec
INSERT OR IGNORE INTO settings (id) VALUES (1)
`

func (q *Queries) InitSettings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initSettings)
	return err
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activities (invoice_id, type, message) VALUES (?, ?, ?)
`

type InsertActivityParams struct {
	InvoiceID sql.NullInt64
	Type      string
	Message   string
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity, arg.InvoiceID, arg.Type, arg.Message)
	return err
}

const insertDraft = `-- name: InsertDraft :one
INSERT INTO email_drafts (invoice_id, stage, subject, body, status)
VALUES (?, ?, ?, ?, ?)
RETURNING id, invoice_id, stage, subject, body, status, created_at, sent_at
`

type InsertDraftParams struct {
	InvoiceID int64
	Stage     string
	Subject   string
	Body      string
	Status    string
}

func (q *Queries) InsertDraft(ctx context.Context, arg InsertDraftParams) (EmailDraft, error) {
	row := q.db.QueryRowContext(ctx, insertDraft,
		arg.InvoiceID,
		arg.Stage,
		arg.Subject,
		arg.Body,
		arg.Status,
	)
	var i EmailDraft
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Stage,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox_emails (invoice_id, invoice_number, to_name, to_email, subject, body, sent_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertOutboxParams struct {
	InvoiceID     int64
	InvoiceNumber string
	ToName        string
	ToEmail       string
	Subject       string
	Body          string
	SentAt        string
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertOutbox,
		arg.InvoiceID,
		arg.InvoiceNumber,
		arg.ToName,
		arg.ToEmail,
		arg.Subject,
		arg.Body,
		arg.SentAt,
	)
	return err
}

const listActivityForInvoice = `-- name: ListActivityForInvoice :many
SELECT id, invoice_id, type, message, created_at FROM activities WHERE invoice_id = ? ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListActivityForInvoice(ctx context.Context, invoiceID sql.NullInt64) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivityForInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Type,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentStats = `-- name: PaymentStats :many
SELECT p.invoice_id, p.amount_cents, p.paid_on, i.client_id, i.issued_on, i.due_on
  FROM payments p JOIN invoices i ON i.id = p.invoice_id
 WHERE i.status = 'paid'
`

type PaymentStatsRow struct {
	InvoiceID   sql.NullInt64
	AmountCents int64
	PaidOn      string
	ClientID    int64
	IssuedOn    string
	DueOn       string
}

func (q *Queries) PaymentStats(ctx context.Context) ([]PaymentStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, paymentStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentStatsRow
	for rows.Next() {
		var i PaymentStatsRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AmountCents,
			&i.PaidOn,
			&i.ClientID,
			&i.IssuedOn,
			&i.DueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoveredTotal = `-- name: RecoveredTotal :one
SELECT COALESCE(SUM(p.amount_cents), 0) AS total FROM payments p
  JOIN invoices i ON i.id = p.invoice_id
 WHERE i.status = 'paid'
`

func (q *Queries) RecoveredTotal(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, recoveredTotal)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const resetDemoData = `-- name: ResetDemoData :exec
DELETE FROM outbox_emails
`

func (q *Queries) ResetDemoData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDemoData)
	return err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
   SET sender_name        = COALESCE(?1, sender_name),
       sender_email       = COALESCE(?2, sender_email),
       default_terms_days = COALESCE(?3, default_terms_days),
       global_mode        = COALESCE(?4, global_mode),
       sim_now            = ?5
 WHERE id = 1
RETURNING id, sender_name, sender_email, default_terms_days, global_mode, sim_now
`

type UpdateSettingsParams struct {
	SenderName       sql.NullString
	SenderEmail      sql.NullString
	DefaultTermsDays sql.NullInt64
	GlobalMode       sql.NullString
	SimNow           sql.NullString
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.SenderName,
		arg.SenderEmail,
		arg.DefaultTermsDays,
		arg.GlobalMode,
		arg.SimNow,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SenderName,
		&i.SenderEmail,
		&i.DefaultTermsDays,
		&i.GlobalMode,
		&i.SimNow,
	)
	return i, err
}
