// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Activity struct {
	ID        int64
	InvoiceID sql.NullInt64
	Type      string
	Message   string
	CreatedAt string
}

type Client struct {
	ID               int64
	Name             string
	Email            string
	PaymentTermsDays int64
	RelationshipNote string
	CreatedAt        string
}

type EmailDraft struct {
	ID        int64
	InvoiceID int64
	Stage     string
	Subject   string
	Body      string
	Status    string
	CreatedAt string
	SentAt    sql.NullString
}

type Invoice struct {
	ID              int64
	ClientID        int64
	Number          string
	AmountCents     int64
	AmountPaidCents int64
	Currency        string
	IssuedOn        string
	DueOn           string
	Status          string
	Notes           string
	AgentState      string
	CurrentStage    sql.NullString
	NextActionOn    sql.NullString
	CreatedAt       string
}

type OutboxEmail struct {
	ID            int64
	InvoiceID     int64
	DraftID       sql.NullInt64
	InvoiceNumber string
	ToName        string
	ToEmail       string
	Subject       string
	Body          string
	SentAt        string
}

type Payment struct {
	ID          int64
	InvoiceID   sql.NullInt64
	AmountCents int64
	PaidOn      string
	Source      string
	Confidence  sql.NullString
	RawText     sql.NullString
	CreatedAt   string
}

type Setting struct {
	ID               int64
	SenderName       string
	SenderEmail      string
	DefaultTermsDays int64
	GlobalMode       string
	SimNow           sql.NullString
}
