// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
)

const applyPartialPayment = `-- name: ApplyPartialPayment :exec
UPDATE invoices SET amount_paid_cents = amount_paid_cents + ?, agent_state = 'chasing'
 WHERE id = ?
`

type ApplyPartialPaymentParams struct {
	AmountPaidCents int64
	ID              int64
}

func (q *Queries) ApplyPartialPayment(ctx context.Context, arg ApplyPartialPaymentParams) error {
	_, err := q.db.ExecContext(ctx, applyPartialPayment, arg.AmountPaidCents, arg.ID)
	return err
}

const cancelPendingDrafts = `-- name: CancelPendingDrafts :exec
UPDATE email_drafts SET status = 'skipped' WHERE invoice_id = ? AND status = 'pending'
`

func (q *Queries) CancelPendingDrafts(ctx context.Context, invoiceID int64) error {
	_, err := q.db.ExecContext(ctx, cancelPendingDrafts, invoiceID)
	return err
}

const listOpenForMatch = `-- name: ListOpenForMatch :many
SELECT i.id AS invoice_id, i.number AS invoice_no, i.client_id, c.name AS client_name,
       i.amount_cents, i.amount_paid_cents, i.due_on
  FROM invoices i
  JOIN clients c ON c.id = i.client_id
 WHERE i.status IN ('scheduled', 'chasing')
 ORDER BY i.due_on ASC
`

type ListOpenForMatchRow struct {
	InvoiceID       int64
	InvoiceNo       string
	ClientID        int64
	ClientName      string
	AmountCents     int64
	AmountPaidCents int64
	DueOn           string
}

func (q *Queries) ListOpenForMatch(ctx context.Context) ([]ListOpenForMatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenForMatch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenForMatchRow
	for rows.Next() {
		var i ListOpenForMatchRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.InvoiceNo,
			&i.ClientID,
			&i.ClientName,
			&i.AmountCents,
			&i.AmountPaidCents,
			&i.DueOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
